ALTER TABLE matches
  ADD COLUMN IF NOT EXISTS round TEXT NOT NULL DEFAULT '',
  ADD COLUMN IF NOT EXISTS venue TEXT NOT NULL DEFAULT '',
  ADD COLUMN IF NOT EXISTS referee TEXT NOT NULL DEFAULT '',
  ADD COLUMN IF NOT EXISTS home_coach TEXT NOT NULL DEFAULT '',
  ADD COLUMN IF NOT EXISTS away_coach TEXT NOT NULL DEFAULT '',
  ADD COLUMN IF NOT EXISTS home_formation TEXT NOT NULL DEFAULT '',
  ADD COLUMN IF NOT EXISTS away_formation TEXT NOT NULL DEFAULT '';
